### ISSUE TITLE
reading only 2M first sequences

### ISSUE THREAD

**Issue by mahdi-b** [WillHarrigan/protein-seq-contact-sites#1]
Your notebook contains the following. Not sure why. I don't think it should.
```python
    if i==2000000:
        break
```

**Comment by mahdi-b** [comment]
Don't forget to fix this, please.

**Comment by WillHarrigan** [comment]
I have resolved this issue. There is a new text file containing updated COG pairs, labeled with today's date (12-16-2022). Most updated version is under commit #: 00cf64a

**Comment by mahdi-b** [comment]
Just FYI, typically you include the hash (code of the new version) in your comment and clove the issue. Leaving it open means it's not fixed. I'll let you close it.
